### ISSUE TITLE
problem with saving results to files when changing between pages

### ISSUE THREAD

**Issue by bpfrd** [luileito/evtrack#12]
Hi, 

Thank you very much for the interesting code. I noticed not all the events (mentioned in the code) are stored and some files are empty, especially when changing between pages. How can I fix it and have all the events stored on all pages?

Best regards,
Behnam

**Comment by luileito** [comment]
Can you provide a minimal working example that replicates what you have noticed? In principle [all events listed here](https://github.com/luileito/evtrack/blob/master/js/src/trackui.js#L51-L59) should be tracked if you set `regularEvents: "*"` in your configuration.

The fact that some log files are empty may be because your `postInterval` value (30 seconds by default) is longer than the user's browsing time. Have you tried to use a smaller value?
